# Generated by Django 4.1.5 on 2023-07-22 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fanpage', '0005_reply_accepted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='categories',
        ),
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ForeignKey(default='123', on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='fanpage.category'),
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
